import Head from 'next/head'
import { useState, useEffect } from 'react';
import ReactMapGL, { GeolocateControl, Marker } from 'react-map-gl';
import { Room } from '@material-ui/icons'

const geolocateControlStyle = {
  right: 10,
  top: 10,
};

export default function Home() {
  
  const mapboxAPI = process.env.MAPBOX

  const [viewport, setViewport] = useState({
    width: "100vw",
    height: "100vh",
    latitude: 38.3566,
    longitude: -121.95,
    zoom: 12
  });

  useEffect(() => {
    const getPins = async () => {
      try {
        const res
      }
    }
  }, [])

  return (
    <div>
      <Head>
        <title>Puddle Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ReactMapGL
      {...viewport}
      mapboxApiAccessToken={mapboxAPI}
      mapStyle={'mapbox://styles/mapbox/streets-v11'}
      onViewportChange={nextViewport => setViewport(nextViewport)}>
        <GeolocateControl
        style={geolocateControlStyle}
        positionOptions={{enableHighAccuracy: true}}
        trackUserLocation={true}
      />
      </ReactMapGL>
    </div>
  )
}
