import Head from 'next/head'
import { useState, useEffect } from 'react';
import ReactMapGL, { GeolocateControl, Marker, Popup } from 'react-map-gl';
import { Room } from '@material-ui/icons'

const geolocateControlStyle = {
  right: 10,
  top: 10,
};

export default function Home() {
  
  const mapboxAPI = process.env.MAPBOX

  const [viewport, setViewport] = useState({
    width: "100vw",
    height: "100vh",
    latitude: 38.3566,
    longitude: -121.95,
    zoom: 12
  });

  const [showPopup, togglePopup] = useState(false);

  // useEffect(() => {
  //   const getPins = async () => {
  //     try {
  //       const res
  //     }
  //   }
  // }, [])

  return (
    <div style={{
      height: '100vh',
      width:'100vw'
    }}>
      <Head>
        <title>Puddle Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ReactMapGL
      {...viewport}
      mapboxApiAccessToken={mapboxAPI}
      width='100%'
      height='100%'
      mapStyle={'mapbox://styles/mapbox/streets-v11'}
      onViewportChange={nextViewport => setViewport(nextViewport)}>
      <Marker 
      latitude={38.35142011381961}
      longitude={-121.99455346165178}
      offsetLeft={-1.25 * viewport.zoom}
      offsetTop={-3.5 * viewport.zoom}
      
      >
        <Room style={{
          fontSize: 3 * viewport.zoom,
          color: 'slateblue '}}/>
      </Marker>
      {/* <Popup
            latitude={38.35142011381961}
            longitude={-121.99455346165178}
            closeButton={true}
            closeOnClick={false}
            anchor='left'
            
      >
        <div className="card">
                  <label>Place</label>
                  <h4 className="place">{p.title}</h4>
                  <label>Review</label>
                  <p className="desc">{p.desc}</p>
                  <label>Rating</label>
                  <div className="stars">
                    {Array(p.rating).fill(<Star className="star" />)}
                  </div>
                  <label>Information</label>
                  <span className="username">
                    Created by <b>{p.username}</b>
                  </span>
                  <span className="date">{format(p.createdAt)}</span>
                </div>

      </Popup> */}
      <GeolocateControl
        style={geolocateControlStyle}
        positionOptions={{enableHighAccuracy: true}}
        trackUserLocation={true}
        auto
      />
      </ReactMapGL>
    </div>
  )
}
